server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://35.72.44.113:5432/jwt?useSSL=false
    username: jwtuser
    password: kjaaaaaaa1

logging:
  level:
    com:
      auth:
        dao: warn

auth:
  jwt:
    SIGNATURE: sgka!7@^#rfdWWidfdfdsjjiiojfweddfdkljfie792888df793ffds*(*90su
